service-activator-integration-cred:
  type: usernamePassword
  data:
    username: '[encrypted:AES256_Fernet]gAAAAABlOAwaSzWv8OrqRZVbdSZCka64GFDWw5kgdauva4rSFJjMHSRKVW5B5FnscIE7-8airNy4YQrDzPV1R4vjWUBQ4pznnQ=='
    password: '[encrypted:AES256_Fernet]gAAAAABlOAwaEiQ4Dy8Xo1Dzti8ZEHOHjMy-byZtCC5YF77HFNcM2fU4X1N5zfp-jrdjZRfdZ4-i91nWR3ia5xEx-GJx0l7Mew=='
tibco-integration-cred:
  type: usernamePassword
  data:
    username: '[encrypted:AES256_Fernet]gAAAAABlOAwaiMcUQ-KozXpyf1Fot69xgf9B1PrpBmDjtue6bGwG3IdbHw9x09K-eEDkyudxj4U1gcBJxR0buR2Tl1HJlh1vGg=='
    password: '[encrypted:AES256_Fernet]gAAAAABlOAway4TkXBrS05owHubIcGNiQkHgfMSD_RP1uk72sBpQ8beOW5LTGYYW7Ow2oGNOjHWKCmlK3tOwzo22ymq6FMaHhQ=='
