version: 24.1
name: argocd-configuration-01
parameters: 
  ARGOCD_USERNAME: x_project_tu
  ARGOCD_PASSWORD: sadasdasdsa
  # WA till autodiscovery in ACH
  PAAS_PLATFORM: 'OPENSHIFT'
  # WA till autodiscovery in ACH
  PAAS_VERSION: 'v4.12'
  # variable for prj-devops-predeploy-app to enable users provisioning
  ARGO_MODE: "true"
