name: "Download artifact"
description: "Get artifact id, download it and unzip to required directory"
author: "Qubership"

inputs:
  sanitized_name:
    description: "Updated environment name without special symbols."
    required: true
    type: string
  full_env:
    description: "Full environment name."
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Get artifact ID that contains environment name
      id: get-artifact
      shell: bash
      run: |
        ENV_ARTIFACT_NAME="${{ inputs.sanitized_name }}"

        ARTIFACTS_JSON=$(curl -s \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts")

        MATCHING_ARTIFACT_ID=$(echo "$ARTIFACTS_JSON" | jq -r --arg name "$ENV_ARTIFACT_NAME" '
          .artifacts
          | map(select(.name | contains($name)))
          | sort_by(.created_at)
          | last
          | .id
        ')

        if [ "$MATCHING_ARTIFACT_ID" = "null" ] || [ -z "$MATCHING_ARTIFACT_ID" ]; then
          echo "Was not able to find artifact with name $ENV_ARTIFACT_NAME"
          exit 1
        fi

        echo "artifact_id=$MATCHING_ARTIFACT_ID" >> $GITHUB_OUTPUT
        echo "Found artifact ID: $MATCHING_ARTIFACT_ID (contains '$ENV_ARTIFACT_NAME' in its name)"

    - name: Download & unzip artifact
      shell: bash
      run: |
        ARTIFACT_URL="https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ steps.get-artifact.outputs.artifact_id }}/zip"

        REDIRECT_URL=$(curl -L -s -o /dev/null -w "%{url_effective}" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "$ARTIFACT_URL")

        curl -L -o artifact.zip "$REDIRECT_URL"

        unzip -o artifact.zip -d "${{ github.workspace }}/environments/${{ inputs.full_env }}"
        rm artifact.zip