version: 23.4
name: consul
parameters:
  CUSTOM_RESOURCE_NAME: "consul"
  DISABLE_FORCE_APPLY: false
  global:
    enabled: true
    name: "consul"
    datacenter: "dc1"
    enablePodSecurityPolicies: false
    tls:
      enabled: false
    acls:
      manageSystemACLs: true
    federation:
      enabled: false
    openshift:
      enabled: true
  server:
    enabled: true
    replicas: "3"
    storage: "10Gi"
    storageClass: "${STORAGE_RWO_CLASS}"
    connect: true
    updatePartition: "0"
    disruptionBudget:
      enabled: true
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "400m"
        memory: "1024M"
    extraConfig:
      limits:
        http_max_conns_per_client: 500
  externalServers:
    enabled: false
  client:
    enabled: true
    nodeSelector:
      node-role.kubernetes.io/worker: ""
    resources:
      requests:
        cpu: "25m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
  dns:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
    service:
      enabled: true
  connectInject:
    enabled: false
  meshGateway:
    enabled: false
  ingressGateways:
    enabled: false
  terminatingGateways:
    enabled: false
  monitoring:
    enabled: true
    monitoringType: "prometheus"
    installDashboard: true
  backupDaemon:
    enabled: false
    storage: "10Gi"
    storageClass: "${STORAGE_RWO_CLASS}"
    username: ""
    password: ""
    backupSchedule: "0 0 * * *"
    evictionPolicy: "0/1d,7d/delete"
    resources:
      requests:
        cpu: "25m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
  consulAclConfigurator:
    enabled: true
    reconcilePeriod: "100"
    serviceName: "consul-acl-configurator-reconcile"
    consul:
      port: "8500"
  integrationTests:
    install: true
    secret:
      aclToken: "${creds.get(\"consul-integrationtests-token-cred\").secret}"
    tags: "crud"
  ESCAPE_SEQUENCE: true
  DISABLE_CRD: false
  ENABLE_PRIVILEGED_PSS: true
  DEPLOY_W_HELM: true
applications: []
