version: 23.4
name: maas
parameters:
  SKIP_VALIDATION: true
  DBAAS_CLUSTER_DBA_CREDENTIALS_PASSWORD: "${creds.get(\"dbaas-cluster-dba-cred\").password}"
  DBAAS_CLUSTER_DBA_CREDENTIALS_USERNAME: "${creds.get(\"dbaas-cluster-dba-cred\").username}"

  GLOBAL_RESOURCE_PROFILE: "'{\"dev\":{\"maas-service\":{\"MEMORY_LIMIT\":\"800Mi\",\"CPU_LIMIT\":\"2000m\",\"CPU_REQUEST\":\"100m\",\"DB_POOL_SIZE\":40}}}'"
  MAAS_ACCOUNT_MANAGER_PASSWORD: "${creds.get(\"maas-account-manager-cred\").password}"
  MAAS_ACCOUNT_MANAGER_USERNAME: "${creds.get(\"maas-account-manager-cred\").username}"
  MAAS_DEPLOYER_CLIENT_PASSWORD: "${creds.get(\"maas-deployer-client-cred\").password}"
  MAAS_DEPLOYER_CLIENT_USERNAME: "${creds.get(\"maas-deployer-client-cred\").username}"
  _rabbitmq_admin_user: "${creds.get(\"rabbitmq-admin-cred\").username}"
  _rabbitmq_admin_pass: "${creds.get(\"rabbitmq-admin-cred\").password}"
  _kafka_admin_user: "${creds.get(\"kafka-admin-cred\").username}"
  _kafka_admin_pass: "${creds.get(\"kafka-admin-cred\").password}"
  _kafka_client_user: "${creds.get(\"kafka-client-cred\").username}"
  _kafka_client_pass: "${creds.get(\"kafka-client-cred\").password}"

  MAAS_RABBIT_INSTANCE_BODY: "{\"apiUrl\":\"http://rabbitmq.${namespace_rabbitmq}:15672/api\",\"amqpUrl\":\"amqp://rabbitmq.${namespace_rabbitmq}:5672\",\"user\":\"${_rabbitmq_admin_user}\",\"password\":\"${_rabbitmq_admin_pass}\",\"default\":true}"
  MAAS_KAFKA_INSTANCE_BODY: "{\"default\":true,\"id\":\"kafka\",\"addresses\":{\"SASL_PLAINTEXT\":[\"kafka.${namespace_kafka}:9092\"]},\"maasProtocol\":\"SASL_PLAINTEXT\",\"credentials\":{\"admin\":[{\"type\":\"SCRAM\",\"username\":\"${_kafka_admin_user}\",\"password\":\"plain:${_kafka_admin_pass}\"}],\"client\":[{\"type\":\"SCRAM\",\"username\":\"${_kafka_client_user}\",\"password\":\"plain:${_kafka_client_pass}\"}]}}"
  ESCAPE_SEQUENCE: true
  DBAAS_ENABLED: true
  API_DBAAS_ADDRESS: "http://dbaas-aggregator.${namespace_dbaas}:8080"
  DBAAS_AGGREGATOR_ADDRESS: "http://dbaas-aggregator.${namespace_dbaas}:8080"
  MONITORING_ENABLED: true
applications: []
