version: 23.4
name: postgresql-dbaas
parameters:
  dbaas:
    install: true
    apiVersion: "v2"
    multiUsers: true
    aggregator:
      registrationAddress: "http://dbaas-aggregator.${namespace_dbaas}:8080"
    resources:
      requests:
        cpu: 250m
        memory: 904Mi
      limits:
        cpu: "1"
        memory: 904Mi
applications: []
