version: 23.4
name: zookeeper
parameters:
  DEPLOY_W_HELM: true
  DISABLE_CRD: false
  global:
    name: "zookeeper"
    enablePersistentVolumeCreation: false
    secrets:
      zooKeeper:
        additionalUsers: "user:pass"
    skipNamespaceValidation: true
  operator:
    affinity: {
      "podAntiAffinity": {
            "requiredDuringSchedulingIgnoredDuringExecution": [
              {
                "labelSelector": {
                  "matchExpressions": [
                    {
                      "key": "component",
                      "operator": "In",
                      "values": [
                          "zookeeper-service-operator"
                      ]
                    }
                  ]
                },
                "topologyKey": "kubernetes.io/hostname"
              }
            ]
          }
        }
  zooKeeper:
    affinity: {
      "podAntiAffinity": {
        "requiredDuringSchedulingIgnoredDuringExecution": [
        {
          "labelSelector": {
            "matchExpressions": [
            {
              "key": "component",
              "operator": "In",
              "values": [
                "zookeeper"
              ]
            }
            ]
          },
          "topologyKey": "kubernetes.io/hostname"
        }
        ]
      }
    }
    replicas: "3"
    quorumAuthEnabled: true
    heapSize: "256"
    jolokiaPort: "9087"
    resources:
      requests:
        cpu: "50m"
        memory: "512Mi"
      limits:
        cpu: "300m"
        memory: "512Mi"
    storage:
      className: 
        - "${STORAGE_RWO_CLASS}"
      size: "10Gi"
  monitoring:
    install: true
    resources:
      requests:
        cpu: "25m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
    monitoringType: "prometheus"
    installGrafanaDashboard: true
  backupDaemon:
    install: false
    backupStorage:
      storageClass: "${STORAGE_RWO_CLASS}"
      persistentVolumeType: "standalone"
      volumeSize: "5Gi"
  integration-tests:
    integrationTests:
      install: true
applications: []
