---
ansible_host: db_ip_address
ansible_ssh_user: andrei
ansible_ssh_pass: samsa
ansible_sudo_pass: samsa
ansible_python_interpreter: /usr/bin/python
postgres_db_name: pgsql_db_name
postgres_user: andrei
postgres_password: samsa
